version: '3.7'
services:
    web.app:
        build:
            context: ./docker/${PHP_VERSION:-7.4}
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: duck-${PHP_VERSION:-7.4}/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - 'duck-sync:/var/www/html'
        networks:
            - duck-network
        depends_on:
            - mariadb
            
    mariadb:
        image: 'mariadb:10.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'duckmariadb:/var/lib/mysql'
        networks:
            - duck-network
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

    redis:
        image: 'redis:6.0-alpine'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        networks:
            - duck-network
          
networks:
    duck-network:
        driver: bridge
volumes:
    duckmariadb:
        driver: local
    duck-sync:
        external: true
